# https://pub.dev/packages/lints
include: package:lints/recommended.yaml

analyzer:
  errors:
    missing_required_param: warning # 必須のパラメータが欠けている場合に警告
    missing_return: warning # 関数やメソッドが戻り値を持たない場合に警告
  language:
    strict-casts: true # 安全でないキャストを防ぐ
    strict-inference: true # Dartが自動で推論できない場合に型を明示的に指定することを要求
    strict-raw-types: true # ジェネリクスの型パラメータが省略された場合に警告

linter:
  rules:
    # includeされているルール: https://github.com/dart-lang/lints/blob/main/lib/recommended.yaml
    - avoid_print # print文の使用を避ける
    - constant_identifier_names # 定数名はすべて大文字でスネークケースを使う
    - avoid_as # 'as' キーワードの使用を避ける
    - prefer_const_constructors # constコンストラクタを推奨
    - prefer_const_literals_to_create_immutables # 不変リスト、マップ、セットをconstで作成することを推奨
    