name: yumemi_flutter_codecheck
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_flavorizr: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  lints: ^4.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

# 更新した場合は、`flutter pub run flutter_flavorizr` を実行
flavorizr:
  flavors:
    dev:
      app:
        name: GitHub Search Dev
      android:
        applicationId: com.example.github_search.dev
      ios:
        bundleId: com.example.github_search.dev
    prd:
      app:
        name: GitHub Search
      android:
        applicationId: com.example.github_search
      ios:
        bundleId: com.example.github_search
