import 'package:flutter/material.dart';

// フォントファミリー
const defaultFontFamily = 'PretendardJp';

const TextTheme appTextTheme = TextTheme(
  displayLarge: TextStyle(
    fontSize: 57,
    decoration: TextDecoration.none,
    fontStyle: FontStyle.normal,
    fontWeight: FontWeight.w400,
    height: 52 / 57,
    letterSpacing: 0,
    fontFamily: defaultFontFamily,
  ),
  displayMedium: TextStyle(
    fontSize: 45,
    decoration: TextDecoration.none,
    fontStyle: FontStyle.normal,
    fontWeight: FontWeight.w400,
    height: 52 / 45,
    letterSpacing: 0,
    fontFamily: defaultFontFamily,
  ),
  displaySmall: TextStyle(
    fontSize: 36,
    decoration: TextDecoration.none,
    fontStyle: FontStyle.normal,
    fontWeight: FontWeight.w400,
    height: 44 / 36,
    letterSpacing: 0,
    fontFamily: defaultFontFamily,
  ),
  headlineLarge: TextStyle(
    fontSize: 32,
    decoration: TextDecoration.none,
    fontStyle: FontStyle.normal,
    fontWeight: FontWeight.w700,
    height: 48 / 32,
    letterSpacing: 0,
    fontFamily: defaultFontFamily,
  ),
  headlineMedium: TextStyle(
    fontSize: 28,
    decoration: TextDecoration.none,
    fontStyle: FontStyle.normal,
    fontWeight: FontWeight.w700,
    height: 42 / 28,
    letterSpacing: 0,
    fontFamily: defaultFontFamily,
  ),
  headlineSmall: TextStyle(
    fontSize: 24,
    decoration: TextDecoration.none,
    fontStyle: FontStyle.normal,
    fontWeight: FontWeight.w700,
    height: 36 / 24,
    letterSpacing: 0,
    fontFamily: defaultFontFamily,
  ),
  titleLarge: TextStyle(
    fontSize: 23,
    decoration: TextDecoration.none,
    fontStyle: FontStyle.normal,
    fontWeight: FontWeight.w700,
    height: 34.5 / 23,
    letterSpacing: 23 * 0.02,
    fontFamily: defaultFontFamily,
  ),
  titleMedium: TextStyle(
    fontSize: 17,
    decoration: TextDecoration.none,
    fontStyle: FontStyle.normal,
    fontWeight: FontWeight.w700,
    height: 25.5 / 17,
    letterSpacing: 17 * 0.02,
    fontFamily: defaultFontFamily,
  ),
  titleSmall: TextStyle(
    fontSize: 16,
    decoration: TextDecoration.none,
    fontStyle: FontStyle.normal,
    fontWeight: FontWeight.w700,
    height: 24 / 16,
    letterSpacing: 16 * 0.04,
    fontFamily: defaultFontFamily,
  ),
  labelLarge: TextStyle(
    fontSize: 15,
    decoration: TextDecoration.none,
    fontStyle: FontStyle.normal,
    fontWeight: FontWeight.w700,
    height: 22.5 / 15,
    letterSpacing: 15 * 0.04,
    fontFamily: defaultFontFamily,
  ),
  labelMedium: TextStyle(
    fontSize: 12,
    decoration: TextDecoration.none,
    fontStyle: FontStyle.normal,
    fontWeight: FontWeight.w700,
    height: 18 / 12,
    fontFamily: defaultFontFamily,
    letterSpacing: 0,
  ),
  labelSmall: TextStyle(
    fontSize: 11,
    decoration: TextDecoration.none,
    fontStyle: FontStyle.normal,
    fontWeight: FontWeight.w700,
    height: 16.5 / 11,
    letterSpacing: 0,
    fontFamily: defaultFontFamily,
  ),
  bodyLarge: TextStyle(
    fontSize: 16,
    decoration: TextDecoration.none,
    fontStyle: FontStyle.normal,
    fontWeight: FontWeight.w400,
    height: 24 / 16,
    letterSpacing: 16 * 0.02,
    fontFamily: defaultFontFamily,
  ),
  bodyMedium: TextStyle(
    fontSize: 14,
    decoration: TextDecoration.none,
    fontStyle: FontStyle.normal,
    fontWeight: FontWeight.w400,
    height: 21 / 14,
    letterSpacing: 14 * 0.02,
    fontFamily: defaultFontFamily,
  ),
  bodySmall: TextStyle(
    fontSize: 11,
    decoration: TextDecoration.none,
    fontStyle: FontStyle.normal,
    fontWeight: FontWeight.w400,
    height: 16.5 / 11,
    letterSpacing: 0,
    fontFamily: defaultFontFamily,
  ),
);
